import { useParams, Link } from 'react-router-dom'
import { useIncidents } from '../context/IncidentContext'
import { SCENARIO_TYPES, SEVERITY_LEVELS } from '../data/scenarios'
import { CIVIL_LIBERTIES_CHECKLIST, INTERAGENCY_PARTNERS } from '../data/decisionCategories'
import { DOCTRINE_COMPLIANCE_CHECKLIST } from '../data/doctrine'
import RiskBadge from '../components/shared/RiskBadge'

const SCENARIO_COLORS = {
  cbrn: { bg: 'bg-amber-500/10', border: 'border-amber-500/30', text: 'text-amber-400' },
  terrorism: { bg: 'bg-blue-500/10', border: 'border-blue-500/30', text: 'text-blue-400' },
  natural_disaster: { bg: 'bg-green-500/10', border: 'border-green-500/30', text: 'text-green-400' },
}

export default function ReviewPage() {
  const { id } = useParams()
  const { state } = useIncidents()
  const incident = state.incidents.find((i) => i.id === id)

  if (!incident) {
    return (
      <div className="flex flex-col items-center justify-center h-64 text-center">
        <p className="text-slate-400 mb-4">Incident not found.</p>
        <Link to="/" className="text-cyan-400 text-sm hover:underline">Return to Dashboard</Link>
      </div>
    )
  }

  const scenarioConfig = Object.values(SCENARIO_TYPES).find((s) => s.id === incident.scenarioType)
  const colors = SCENARIO_COLORS[incident.scenarioType] || SCENARIO_COLORS.cbrn
  const partners = INTERAGENCY_PARTNERS[incident.scenarioType] || []

  const completedChecks = Object.values(incident.civilLiberties).filter(Boolean).length
  const totalChecks = CIVIL_LIBERTIES_CHECKLIST.length
  const compliancePercent = totalChecks > 0 ? Math.round((completedChecks / totalChecks) * 100) : 0

  const doctrineCompliance = incident.doctrineCompliance || {}
  const completedDoctrineChecks = Object.values(doctrineCompliance).filter(Boolean).length
  const totalDoctrineChecks = DOCTRINE_COMPLIANCE_CHECKLIST.length
  const doctrineCompliancePercent = totalDoctrineChecks > 0 ? Math.round((completedDoctrineChecks / totalDoctrineChecks) * 100) : 0

  const coordinated = Object.values(incident.agencyCoordination).filter((s) => s !== 'not-contacted').length
  const totalPartners = partners.length

  const duration = incident.completedAt
    ? Math.round((new Date(incident.completedAt) - new Date(incident.createdAt)) / 60000)
    : Math.round((Date.now() - new Date(incident.createdAt)) / 60000)

  function formatDuration(mins) {
    if (mins < 60) return `${mins}m`
    const h = Math.floor(mins / 60)
    const m = mins % 60
    return `${h}h ${m}m`
  }

  function handleExport() {
    const lines = [
      `AEGIS INCIDENT REVIEW REPORT`,
      `${'='.repeat(50)}`,
      ``,
      `Incident: ${incident.name}`,
      `Type: ${scenarioConfig?.fullName || incident.scenarioType}`,
      `Location: ${incident.location}`,
      `Severity: ${incident.severity}`,
      `Status: ${incident.status}`,
      `Created: ${new Date(incident.createdAt).toLocaleString()}`,
      incident.completedAt ? `Completed: ${new Date(incident.completedAt).toLocaleString()}` : '',
      `Duration: ${formatDuration(duration)}`,
      ``,
      `DECISIONS (${incident.decisions.length})`,
      `${'-'.repeat(30)}`,
      ...incident.decisions.map((d, i) =>
        `${i + 1}. [${d.category}] ${d.summary}${d.rationale ? `\n   Rationale: ${d.rationale}` : ''}\n   By: ${d.authorizedBy} at ${new Date(d.timestamp).toLocaleString()}`
      ),
      ``,
      `CIVIL LIBERTIES COMPLIANCE: ${compliancePercent}% (${completedChecks}/${totalChecks})`,
      `${'-'.repeat(30)}`,
      ...CIVIL_LIBERTIES_CHECKLIST.map((c) =>
        `[${incident.civilLiberties[c.id] ? 'X' : ' '}] ${c.item}`
      ),
      ``,
      `DOCTRINE COMPLIANCE: ${doctrineCompliancePercent}% (${completedDoctrineChecks}/${totalDoctrineChecks})`,
      `${'-'.repeat(30)}`,
      ...DOCTRINE_COMPLIANCE_CHECKLIST.map((c) =>
        `[${doctrineCompliance[c.id] ? 'X' : ' '}] ${c.item}`
      ),
      ``,
      `INTERAGENCY COORDINATION`,
      `${'-'.repeat(30)}`,
      ...partners.map((p) => {
        const status = incident.agencyCoordination[p.id] || 'not-contacted'
        return `${p.name}: ${status} - ${p.role}`
      }),
      ``,
      `AUDIT TRAIL (${incident.auditLog.length} entries)`,
      `${'-'.repeat(30)}`,
      ...incident.auditLog.map((e) =>
        `[${new Date(e.timestamp).toLocaleString()}] ${e.action} - ${e.details} (${e.user})`
      ),
      ``,
      `${'='.repeat(50)}`,
      `Generated by AEGIS Framework v1.0`,
      `All AI outputs were advisory only. Human authority was required for all decisions.`,
    ].filter((l) => l !== undefined)

    navigator.clipboard.writeText(lines.join('\n')).then(() => {
      alert('Report copied to clipboard.')
    }).catch(() => {
      // Fallback: open in new window
      const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `aegis-review-${incident.name.replace(/\s+/g, '-').toLowerCase()}.txt`
      a.click()
      URL.revokeObjectURL(url)
    })
  }

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <Link to="/" className="text-xs text-slate-500 hover:text-cyan-400 no-underline">Dashboard</Link>
            <span className="text-xs text-slate-700">/</span>
            <span className="text-xs text-slate-400">Incident Review</span>
          </div>
          <div className="flex items-center gap-3">
            <span className="text-2xl">{scenarioConfig?.icon}</span>
            <div>
              <h1 className="text-xl font-bold text-slate-100">{incident.name}</h1>
              <p className="text-xs text-slate-400">{scenarioConfig?.fullName} — {incident.location}</p>
            </div>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <span className={`text-xs px-2.5 py-1 rounded-full border font-medium ${
            incident.status === 'completed'
              ? 'bg-green-400/10 text-green-400 border-green-400/30'
              : 'bg-amber-400/10 text-amber-400 border-amber-400/30'
          }`}>
            {incident.status === 'completed' ? 'Completed' : 'Active'}
          </span>
          <button
            onClick={handleExport}
            className="px-4 py-2 bg-cyan-500/10 text-cyan-400 border border-cyan-500/30 rounded-lg text-xs font-medium cursor-pointer hover:bg-cyan-500/20 transition-colors"
          >
            Export Report
          </button>
        </div>
      </div>

      {/* Summary Stats */}
      <div className="grid grid-cols-6 gap-3">
        {[
          { label: 'Severity', value: SEVERITY_LEVELS[incident.severity]?.label || incident.severity, color: 'text-red-400' },
          { label: 'Decisions', value: incident.decisions.length, color: 'text-cyan-400' },
          { label: 'Duration', value: formatDuration(duration), color: 'text-purple-400' },
          { label: 'Compliance', value: `${compliancePercent}%`, color: compliancePercent === 100 ? 'text-green-400' : 'text-amber-400' },
          { label: 'Doctrine', value: `${doctrineCompliancePercent}%`, color: doctrineCompliancePercent === 100 ? 'text-green-400' : 'text-amber-400' },
          { label: 'Agencies', value: `${coordinated}/${totalPartners}`, color: 'text-blue-400' },
        ].map((s) => (
          <div key={s.label} className="bg-slate-900/60 border border-slate-800 rounded-xl p-3 text-center">
            <p className="text-[10px] text-slate-500 uppercase tracking-wider">{s.label}</p>
            <p className={`text-lg font-bold font-mono ${s.color}`}>{s.value}</p>
          </div>
        ))}
      </div>

      {/* Decision Timeline */}
      <section className="bg-slate-900/60 border border-slate-800 rounded-xl p-5">
        <h2 className="text-sm font-bold text-slate-300 mb-4">Decision Timeline</h2>
        {incident.decisions.length === 0 ? (
          <p className="text-xs text-slate-600 italic">No decisions were recorded for this incident.</p>
        ) : (
          <div className="relative">
            <div className="absolute left-3 top-2 bottom-2 w-px bg-slate-800" />
            <div className="space-y-4">
              {incident.decisions.map((d, i) => (
                <div key={d.id} className="flex items-start gap-4 relative">
                  <div className="w-6 h-6 rounded-full bg-cyan-500/20 border border-cyan-500/40 flex items-center justify-center shrink-0 z-10">
                    <span className="text-[10px] text-cyan-400 font-bold">{i + 1}</span>
                  </div>
                  <div className="flex-1 bg-slate-800/40 rounded-lg p-3">
                    <div className="flex items-center justify-between mb-1">
                      <span className="text-[10px] text-cyan-400 font-semibold uppercase">{d.category}</span>
                      <span className="text-[10px] text-slate-600 font-mono">{new Date(d.timestamp).toLocaleString()}</span>
                    </div>
                    <p className="text-sm text-slate-200 font-medium">{d.summary}</p>
                    {d.rationale && <p className="text-xs text-slate-400 mt-1">{d.rationale}</p>}
                    <p className="text-[10px] text-slate-600 mt-1.5">Authorized by: {d.authorizedBy}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </section>

      {/* Governance Report */}
      <div className="grid grid-cols-2 gap-4">
        {/* Civil Liberties */}
        <section className="bg-slate-900/60 border border-slate-800 rounded-xl p-5">
          <div className="flex items-center justify-between mb-3">
            <h2 className="text-sm font-bold text-slate-300">Civil Liberties Compliance</h2>
            <span className={`text-xs font-mono px-2 py-0.5 rounded ${
              compliancePercent === 100 ? 'bg-green-400/20 text-green-400' : 'bg-amber-400/20 text-amber-400'
            }`}>
              {compliancePercent}%
            </span>
          </div>
          <div className="space-y-2">
            {CIVIL_LIBERTIES_CHECKLIST.map((check) => (
              <div key={check.id} className="flex items-start gap-2">
                <span className={`text-sm mt-0.5 shrink-0 ${incident.civilLiberties[check.id] ? 'text-green-400' : 'text-slate-600'}`}>
                  {incident.civilLiberties[check.id] ? '✓' : '○'}
                </span>
                <span className={`text-xs ${incident.civilLiberties[check.id] ? 'text-slate-300' : 'text-slate-500'}`}>
                  {check.item}
                </span>
              </div>
            ))}
          </div>
        </section>

        {/* Doctrine Compliance */}
        <section className="bg-slate-900/60 border border-slate-800 rounded-xl p-5">
          <div className="flex items-center justify-between mb-3">
            <h2 className="text-sm font-bold text-slate-300">Doctrine Compliance</h2>
            <span className={`text-xs font-mono px-2 py-0.5 rounded ${
              doctrineCompliancePercent === 100 ? 'bg-green-400/20 text-green-400' : 'bg-amber-400/20 text-amber-400'
            }`}>
              {doctrineCompliancePercent}%
            </span>
          </div>
          <div className="space-y-2">
            {DOCTRINE_COMPLIANCE_CHECKLIST.map((check) => (
              <div key={check.id} className="flex items-start gap-2">
                <span className={`text-sm mt-0.5 shrink-0 ${doctrineCompliance[check.id] ? 'text-green-400' : 'text-slate-600'}`}>
                  {doctrineCompliance[check.id] ? '✓' : '○'}
                </span>
                <span className={`text-xs ${doctrineCompliance[check.id] ? 'text-slate-300' : 'text-slate-500'}`}>
                  {check.item}
                </span>
              </div>
            ))}
          </div>
        </section>
      </div>

      {/* Agency Coordination */}
      <section className="bg-slate-900/60 border border-slate-800 rounded-xl p-5">
        <h2 className="text-sm font-bold text-slate-300 mb-3">Interagency Coordination</h2>
        <div className="space-y-2">
          {partners.map((p) => {
            const status = incident.agencyCoordination[p.id] || 'not-contacted'
            const statusColors = {
              'not-contacted': 'text-slate-500',
              'notified': 'text-amber-400',
              'coordinating': 'text-blue-400',
              'on-scene': 'text-green-400',
            }
            return (
              <div key={p.id} className="flex items-center justify-between">
                <div>
                  <p className="text-xs font-medium text-slate-200">{p.name}</p>
                  <p className="text-[10px] text-slate-500">{p.role}</p>
                </div>
                <span className={`text-[10px] font-semibold capitalize ${statusColors[status]}`}>
                  {status.replace('-', ' ')}
                </span>
              </div>
            )
          })}
        </div>
      </section>

      {/* Framework Compliance Checklist */}
      <section className="bg-slate-900/60 border border-slate-800 rounded-xl p-5">
        <h2 className="text-sm font-bold text-slate-300 mb-4">Framework Compliance Summary</h2>
        <div className="grid grid-cols-3 gap-4">
          {[
            {
              layer: 'Decision Definition',
              color: 'cyan',
              checks: [
                { label: 'Decision categories addressed', passed: incident.decisions.length > 0 },
                { label: 'Rationale documented for decisions', passed: incident.decisions.some((d) => d.rationale) },
                { label: 'Authorization recorded', passed: incident.decisions.some((d) => d.authorizedBy) },
                { label: 'Scenario-specific questions considered', passed: incident.decisions.length >= 2 },
              ],
            },
            {
              layer: 'Analytical Support',
              color: 'purple',
              checks: [
                { label: 'AI outputs marked as advisory', passed: true },
                { label: 'Data sources transparent', passed: true },
                { label: 'Confidence levels displayed', passed: true },
                { label: 'Human override capability present', passed: true },
              ],
            },
            {
              layer: 'Governance & Oversight',
              color: 'emerald',
              checks: [
                { label: 'Civil liberties checklist completed', passed: compliancePercent === 100 },
                { label: 'Doctrine compliance checklist completed', passed: doctrineCompliancePercent === 100 },
                { label: 'Interagency coordination initiated', passed: coordinated > 0 },
                { label: 'Audit trail maintained', passed: incident.auditLog.length > 0 },
                { label: 'Decision log populated', passed: incident.decisions.length > 0 },
              ],
            },
          ].map((section) => (
            <div key={section.layer} className={`border rounded-lg p-3 ${
              section.color === 'cyan' ? 'border-cyan-500/20 bg-cyan-500/5' :
              section.color === 'purple' ? 'border-purple-500/20 bg-purple-500/5' :
              'border-emerald-500/20 bg-emerald-500/5'
            }`}>
              <h3 className={`text-xs font-bold mb-2 ${
                section.color === 'cyan' ? 'text-cyan-400' :
                section.color === 'purple' ? 'text-purple-400' :
                'text-emerald-400'
              }`}>{section.layer}</h3>
              <div className="space-y-1.5">
                {section.checks.map((check) => (
                  <div key={check.label} className="flex items-center gap-2">
                    <span className={`text-xs ${check.passed ? 'text-green-400' : 'text-slate-600'}`}>
                      {check.passed ? '✓' : '○'}
                    </span>
                    <span className={`text-[11px] ${check.passed ? 'text-slate-300' : 'text-slate-500'}`}>
                      {check.label}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Audit Trail */}
      <section className="bg-slate-900/60 border border-slate-800 rounded-xl p-5">
        <h2 className="text-sm font-bold text-slate-300 mb-4">Complete Audit Trail</h2>
        <div className="space-y-1.5">
          {incident.auditLog.map((entry) => (
            <div key={entry.id} className="flex items-start gap-3 text-xs">
              <span className="text-slate-600 font-mono shrink-0 w-36">
                {new Date(entry.timestamp).toLocaleString()}
              </span>
              <span className="text-slate-500 shrink-0 w-14">{entry.user}</span>
              <span className="text-slate-300">{entry.action}</span>
              <span className="text-slate-600">— {entry.details}</span>
            </div>
          ))}
        </div>
      </section>

      {/* Footer */}
      <div className="advisory-banner rounded-lg p-3 text-center">
        <p className="text-[10px] text-cyan-400">
          AEGIS Framework v1.0 — All AI-generated analysis was advisory only. Human decision authority was maintained throughout this incident.
        </p>
      </div>
    </div>
  )
}
